doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        server_version: '5.7'
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            product:
                is_bundle: false
                type: yml
                dir: '%kernel.project_dir%/src/Infrastructure/Product/resources/orm'
                prefix: 'App\Domain\Product\Model'
            taxonomy:
                is_bundle: false
                type: yml
                dir: '%kernel.project_dir%/src/Infrastructure/Taxonomy/resources/orm'
                prefix: 'App\Domain\Taxonomy\Model'