version: '3.7'
services:
    mysql:
        image: mysql:5.6
        volumes:
            - .docker/data/db:/var/lib/mysql
        command:
            - '--default-authentication-plugin=mysql_native_password'
            - '--lower_case_table_names=1'
        ports:
            - 33060:3306
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: database
    php:
        build: .docker/php/
        volumes:
            - ./:/var/www/html
            - .docker/php/conf/timezone.ini:/usr/local/etc/php/conf.d/timezone.ini
            - .docker/php/conf/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
            - .docker/php/conf/log.ini:/usr/local/etc/php/conf.d/log.ini
        ports:
            - 80:80
        environment:
            - APACHE_DOCUMENT_ROOT=/var/www/html/public
            - XDEBUG_CONFIG=remote_host=10.254.254.254
            - PHP_IDE_CONFIG=serverName=docker_ecommerce
        depends_on:
            - mysql