services:
    app.product.service.product_to_array:
        class: 'App\Application\Product\Service\ProductToArrayConverter'

    app.product.service.product_factory:
        class: App\Domain\Product\Service\ProductFactory
        arguments:
            - '@app.product.repository.doctrine'
            - '@app.common.service.ramsey_uuid_generator'
            - '@app.taxonomy.repository.doctrine'

    app.product.command.get_products:
        class: App\Application\Product\Command\GetProducts\GetProductsCommandHandler
        tags:
            - { name: tactician.handler, typehints: true }
        arguments:
            - '@app.product.repository.doctrine'
            - '@app.product.service.product_to_array'
            - '@app.taxonomy.repository.doctrine'

    app.product.command.create_product:
        class: App\Application\Product\Command\CreateProduct\CreateProductCommandHandler
        tags:
            - { name: tactician.handler, typehints: true }
        arguments:
            - '@app.product.service.product_factory'
            - '@app.product.service.product_to_array'

    app.product.repository.doctrine:
        class: App\Infrastructure\Product\Repository\DoctrineProductRepository
        arguments:
            - '@Doctrine\Persistence\ManagerRegistry'