services:
    app.product_to_array_converter:
        class: 'App\Application\Product\Service\ProductToArrayConverter'

    app.product_paginated_result_to_array_converter:
        class: 'App\Application\Product\Service\ProductPaginatedResultToArrayConverter'
        arguments:
            - '@app.product_to_array_converter'

    app.get_products_command_to_product_filters_converter:
        class: 'App\Application\Product\Service\GetProductsCommandToProductFiltersConverter'
        arguments:
            - '@app.doctrine_taxonomy_repository'

    app.get_products_command_to_pagination_converter:
        class: 'App\Application\Product\Service\GetProductsCommandToPaginationConverter'
        arguments:
            - '@app.paginator_factory'

    app.product_factory:
        class: App\Domain\Product\Service\ProductFactory
        arguments:
            - '@app.doctrine_product_repository'
            - '@app.ramsey_uuid_generator'
            - '@app.doctrine_taxonomy_repository'

    app.get_products_command_handler:
        class: App\Application\Product\Command\GetProducts\GetProductsCommandHandler
        tags:
            - { name: tactician.handler, typehints: true }
        arguments:
            - '@app.doctrine_product_repository'
            - '@app.get_products_command_to_product_filters_converter'
            - '@app.get_products_command_to_pagination_converter'
            - '@app.product_paginated_result_to_array_converter'

    app.create_product_command_handler:
        class: App\Application\Product\Command\CreateProduct\CreateProductCommandHandler
        tags:
            - { name: tactician.handler, typehints: true }
        arguments:
            - '@app.product_factory'
            - '@app.product_to_array_converter'

    app.doctrine_product_repository:
        class: App\Infrastructure\Product\Repository\DoctrineProductRepository
        arguments:
            - '@Doctrine\Persistence\ManagerRegistry'