services:
    app.ramsey_uuid_generator:
        class: 'App\Infrastructure\Common\Service\RamseyUuidGenerator'

    app.paginator_factory:
        class: 'App\Domain\Common\Service\PaginationFactory'

    app.paginated_result_to_array_converter:
        class: 'App\Application\Common\Service\PaginatedResultToArrayConverter'