parameters:
    project_path: '%kernel.project_dir%'
    uploads_relative_path: '/public/images'
services:
    app.ramsey_uuid_generator:
        class: 'App\Infrastructure\Common\Service\RamseyUuidGenerator'

    app.paginator_factory:
        class: 'App\Domain\Common\Service\PaginationFactory'

    app.paginated_result_to_array_converter:
        class: 'App\Application\Common\Service\PaginatedResultToArrayConverter'

    app.file_system_base_64_to_mime_type_converter:
        class: 'App\Infrastructure\Common\Service\FileSystemBase64ToMimeTypeConverter'

    app.file_system_base_64_image_uploader:
        class: 'App\Infrastructure\Common\Service\FileSystemBase64ImageUploader'
        arguments:
            - '%project_path%'
            - '%uploads_relative_path%'
            - '@app.file_system_base_64_to_mime_type_converter'
            - '@app.ramsey_uuid_generator'